baseURL = 'https://donreno.github.io'
languageCode = 'en-us'
title = "DonRenito's blog"
theme = 'bare'
author = "Don Renito (Renato San Martin)"

[taxonomies]
  tag = "tags"

[params]
mainSections = ["post"]
author = "DonReno"
authorAKA="Renato San Martin"
email = "renatosmb@gmail.com"
repoLink = "https://github.com/donreno/donreno.github.io"
description = "Non-IA Alien beast"
# PostCSS is harder than it should be to get working on a theme
# example site. It's easy on _your_ site.
postcss = false
# Include the author name in the <title> of articles
includeAuthorInTitle = true
disableAttribution=true
hero_colour = "link"

[[params.social]]
icon = "github"
url = "https://github.com/donreno/"

[[params.social]]
icon = "linkedin"
url = "https://www.linkedin.com/in/renato-san-martin-37306017/"